local unitDef = {
	unitname                      = "missilethermobaric",
	name                          = "Rupture",
	description                   = "Thermobaric Missile",
	buildCostMetal                = 2200,
	builder                       = false,
	buildingGroundDecalDecaySpeed = 30,
	buildingGroundDecalSizeX      = 3,
	buildingGroundDecalSizeY      = 3,
	buildingGroundDecalType       = "napalmmissile_aoplane.dds",
	buildPic                      = "missilekinetic.png",
	category                      = "SINK UNARMED",
	collisionVolumeOffsets        = "0 10 0",
	collisionVolumeScales         = "10 33 10",
	collisionVolumeType	          = "CylY",
	customParams                  = {
		aimposoffset   = "0 55 -15",
		midposoffset   = "0 45 -15",
		mobilebuilding = "1",
		outline_x = 55,
		outline_y = 80,
		outline_yoff = 55,
	},
	explodeAs                     = "BIG_UNIT",
	footprintX                    = 1,
	footprintZ                    = 1,
	iconType                      = "cruisemissilesmall",
	idleAutoHeal                  = 5,
	idleTime                      = 1800,
	maxDamage                     = 1000,
	maxSlope                      = 18,
	minCloakDistance              = 150,
	objectName                    = "wep_kinetic_driver.dae",
	script                        = "missilethermobaric.lua",
	selfDestructAs                = "BIG_UNIT",
	sfxtypes                      = {
		explosiongenerators = {
			"custom:RAIDMUZZLE",
		},
	},
	sightDistance                 = 0,
	useBuildingGroundDecal        = false,
	yardMap                       = "o",
	weapons                       = {
		{
			def                = "WEAPON",
			badTargetCategory  = "SWIM LAND SHIP HOVER",
			onlyTargetCategory = "SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP",
		},
	},
	weaponDefs                    = {
		WEAPON = {
			name                    = "Thermobaric Warhead",
			cegTag                  = "thermobarictrail",
			areaOfEffect            = 1500,
			avoidFriendly           = false,
			avoidground             = false,
			avoidfeature            = false,
			collideFriendly         = false,
			craterBoost             = 0,
			craterMult              = 0,
			customParams        	  = {	
				light_color = "1.35 0.5 0.36",
				light_radius = 550,
				cruise_minterrainheight = 300,
				cruisealt = 1000,
				cruisedist = 4000,
			},
			damage                  = {
				default = 2200.01,
			},
			edgeEffectiveness       = 0.4,
			explosionGenerator      = "custom:LONDON_THERMOBARIC",
			fireStarter             = 220,
			flightTime              = 30,
			impulseBoost            = 0,
			impulseFactor           = 0,
			interceptedByShieldType = 2,
			model                   = "wep_kinetic_driver.dae",
			noSelfDamage            = true,
			range                   = 4000,
			-- reloadtime              = 10,
			smokeTrail              = false,
			soundHit                = [[explosion/thermobaric3.ogg]],
			soundStart              = "SiloLaunch",
			startVelocity           = 20,
			tolerance               = 4000,
			turnrate                = 16000,
			tracks                  = true,
			weaponAcceleration      = 400,
			weaponType              = "StarburstLauncher",
			weaponVelocity          = 1500,
		},
	},
	featureDefs                   = {},
}

return { missilethermobaric = unitDef }
